---
- hosts: web

  tasks:

  - name: disable site
    shell: a2dissite {{ domain }}.conf
    sudo: yes
    notify:
      - restart apache

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
      sudo: yes

- hosts: dns

  tasks:

  - name: remove file from hosts
    shell: "sed -i '/{{ domain }}/d' /etc/hosts"
    sudo: yes
    notify:
      - restart dnsmasq

  handlers:
  - name: restart dnsmasq
    service: name=dnsmasq state=restarted
    sudo: yes
